# $schema: https://www.rubyschema.org/rubocop.json

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Lint/SymbolConversion:
  EnforcedStyle: consistent

Layout/HashAlignment:
  Enabled: true
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Enabled: false
